export const ACTION_TYPE = {
  SET_DATA_FIRST: "SET_DATA_FIRST",
  SET_DATA_SECOND: "SET_DATA_SECOND",
  SET_DATA_THIRD: "SET_DATA_THIRD",
  SEARCH_DATA: "SEARCH_DATA",
  REMOVE_SEARCH_DATA: "REMOVE_SEARCH_DATA",
  SHOW_NAVBAR_DIV_BOX: "SHOW_NAVBAR_DIV_BOX",
  SELECTED_IMAGES: "SELECTED_IMAGES",
  OPEN_MODEL_TAB: "OPEN_MODEL_TAB",
};
